name: dailybible
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.9+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.2
  http: ^1.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  flex_color_scheme: ^8.2.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  easy_localization: ^3.0.3
  flutter_timezone: ^4.0.0
  google_mobile_ads: ^6.0.0
  screenshot: ^3.0.0
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.8
  in_app_purchase_android: ^0.4.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.3.1
  package_info_plus: any
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4
flutter_icons:
    ios: true
    android: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/fonts/
    - assets/logo.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf 